name: Go Checks

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  run-tests:
    name: go test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run Tests
        run: go test ./...

  frontend-checks:
    name: frontend checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Run frontend checks
        run: make frontend-check

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6.2
